### ISSUE TITLE
InputService Methods

### ISSUE THREAD

**Issue by movsar** [movsar/csprojects#1]
1. Для того чтобы сделать код более стабильным, нужно добавить методы в InputService для принятия данных от пользователя с валидацией:
	
	* DateTime? GetDate()
	* string? GetString()
	* int? GetInt()
	* double? GetDouble()

Каждый метод должен использовать тип.TryParse() и если не получилось взять значение необходимого типа, вернуть null.

2. В задаче CakesImproved из проекта Part4, нужно поменять все вызовы Console.ReadLine() на соответствующие вызовы созданных методов InputService'a, и проверять получаемые значения на null. Если null, надо сообщать об ошибке и выйти из текущего метода.

3. Переименовать SelectMode() в GetOption(). В VS можно Ctrl+R, R нажать для рефакторинга, иначе проверьте что вы заменили название везде где использовался этот метод.

**Comment by FraintSaad** [comment]
Сделал
